config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :accountings

  root 'accountings#index'
  get 'dashboard'=>'accountings#dashboard'

end

app/models/accounting.rb
class Accounting < ActiveRecord::Base
  belongs_to :user

  def self.dashboard(current_user)
    data = Accounting.select("title, sum(expense) as total").where({ user: current_user }).group("title")
    data.map{|d|[ d.title, d.total ]}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :accountings
end

app/controllers/accountings_controller.rb
class AccountingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_accounting, only: [:show, :edit, :update, :destroy]

  # GET /accountings
  # GET /accountings.json
  def index
    @accountings = Accounting.where(user: current_user).last(5)
  end
  def dashboard
    @data=Accounting.dashboard(current_user)
  end
  # GET /accountings/1
  # GET /accountings/1.json
  def show
  end

  # GET /accountings/new
  def new
    @accounting = Accounting.new
  end

  # GET /accountings/1/edit
  def edit
  end

  # POST /accountings
  # POST /accountings.json
  def create
    @accounting =  current_user.accountings.new(accounting_params)

    respond_to do |format|
      if @accounting.save
        format.html { redirect_to @accounting, notice: 'Accounting was successfully created.' }
        format.json { render :show, status: :created, location: @accounting }
      else
        format.html { render :new }
        format.json { render json: @accounting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accountings/1
  # PATCH/PUT /accountings/1.json
  def update
    respond_to do |format|
      if @accounting.update(accounting_params)
        format.html { redirect_to @accounting, notice: 'Accounting was successfully updated.' }
        format.json { render :show, status: :ok, location: @accounting }
      else
        format.html { render :edit }
        format.json { render json: @accounting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accountings/1
  # DELETE /accountings/1.json
  def destroy
    @accounting.destroy
    respond_to do |format|
      format.html { redirect_to accountings_url, notice: 'Accounting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_accounting
    @accounting = Accounting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def accounting_params
    params.require(:accounting).permit(:title, :expense, :time)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/accountings_helper.rb
module AccountingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accountings/_form.html.erb
<%= form_for(@accounting) do |f| %>
  <% if @accounting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accounting.errors.count, "error") %> prohibited this accounting from being saved:</h2>

      <ul>
      <% @accounting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.select :title, options_for_select(["home", "personal", "car", "shopping", "food"]) %>
  </div>
  <div class="field">
    <%= f.label :expense %><br>
    <%= f.number_field :expense %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accountings/dashboard.html.erb
<h2>Dashboard</h2>

<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>

<script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>

 

<script type="text/javascript">
    $(function () {
    $(document).ready(function () {
        // Build the chart
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'Expense'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false
                    },
                    showInLegend: true
                }
            },
            series: [{
                type: 'pie',
                name: 'Browser share',
                data: <%= @data.to_json.html_safe%>
            }]
        });
    });
});
</script>

app/views/accountings/edit.html.erb
<h1>Editing Accounting</h1>

<%= render 'form' %>

<%= link_to 'Show', @accounting %> |
<%= link_to 'Back', accountings_path %>

app/views/accountings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accountings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Expense</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accountings.each do |accounting| %>
      <tr>
        <td><%= accounting.title %></td>
        <td><%= accounting.expense %></td>
        <td><%= accounting.time %></td>
        <td><%= link_to 'Show', accounting %></td>
        <td><%= link_to 'Edit', edit_accounting_path(accounting) %></td>
        <td><%= link_to 'Destroy', accounting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accounting', new_accounting_path %>

app/views/accountings/new.html.erb
<h1>New Accounting</h1>

<%= render 'form' %>

<%= link_to 'Back', accountings_path %>

app/views/accountings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @accounting.title %>
</p>

<p>
  <strong>Expense:</strong>
  <%= @accounting.expense %>
</p>

<p>
  <strong>Time:</strong>
  <%= @accounting.time %>
</p>

<%= link_to 'Edit', edit_accounting_path(@accounting) %> |
<%= link_to 'Back', accountings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Account</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Home", root_path %>
	<% if user_signed_in? %>
	<%= link_to "登出", destroy_user_session_path,method:'delete' %>
	<%= link_to "Dashboard", dashboard_path %>
	<% else %>
	<%= link_to "註冊", new_user_registration_path %>
	<%= link_to "登入", new_user_session_path %>
	<% end %>
<%= yield %>

</body>
</html>